name: on-push-to-branch
concurrency:
  group: on-push-to-branch
  cancel-in-progress: true

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - '**.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
          runTests: false
          wait-on: 'http://localhost:5173'
      - name: Cypress run E2E tests
        uses: cypress-io/github-action@v6
        with:
          install: false
      - run: killall -9 node
      - name: Cypress run component tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: weatherstationproject/web-ui
          tags: type=raw,value=development
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}